version: '3'

services:
  myapp:
    build: ./
    ports:
      - "8080:8080"
    links:
      - database
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
      
  database:
    image: mongo
    ports:
      - "27017:27017"